### ISSUE TITLE
building for kernel 4.2 fails due to changes in tty_name() 

### ISSUE THREAD

**Issue by sergeleschinsky** [CERN-CERT/activity_klog#4]
Hello.

This commit (https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=429b474990cb4e5e8cfe2352daf649d0599cccb6) changed tty_name().

**Comment by Feandil** [comment]
Hi,

Thanks for the report. It seems that I forgot to push some fixes I made locally, sorry for this.
73b9d8386e9eb375991d88ad182af32d5379bb00 should fix the tty_name issue.

Note that due to our environment here, we were not able to test such patches in details.
